name: TikTok to YouTube Live

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install FFmpeg and yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          python3 -m pip install -U yt-dlp

      - name: TikTok to YouTube
        env:
          TIKTOK_URL: ${{ secrets.TIKTOK_URL }}
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          while true
          do
            echo "======================================"
            echo "Getting fresh TikTok LIVE stream URL..."
            echo "======================================"

            STREAM_URL=$(yt-dlp \
              --no-playlist \
              -f "best" \
              -g \
              "$TIKTOK_URL" 2>/dev/null | head -n 1)

            if [ -z "$STREAM_URL" ]; then
              echo "TikTok stream URL not available."
              echo "Retrying in 20 seconds..."
              sleep 20
              continue
            fi

            echo "Fresh TikTok stream URL obtained."
            echo "Starting YouTube LIVE..."

            ffmpeg \
              -hide_banner \
              -loglevel info \
              -re \
              -rw_timeout 60000000 \
              -reconnect 1 \
              -reconnect_at_eof 1 \
              -reconnect_streamed 1 \
              -reconnect_delay_max 15 \
              -user_agent "Mozilla/5.0" \
              -i "$STREAM_URL" \
              -c:v libx264 \
              -preset veryfast \
              -pix_fmt yuv420p \
              -b:v 4500k \
              -maxrate 4500k \
              -bufsize 9000k \
              -r 30 \
              -g 60 \
              -keyint_min 60 \
              -sc_threshold 0 \
              -c:a aac \
              -b:a 128k \
              -ar 44100 \
              -f flv \
              "rtmps://a.rtmps.youtube.com/live2/${YOUTUBE_STREAM_KEY}"

            echo "FFmpeg stopped."
            echo "Retrying with a fresh TikTok URL in 10 seconds..."
            sleep 10
          done
