      - name: TikTok to YouTube
        env:
          TIKTOK_URL: ${{ secrets.TIKTOK_URL }}
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          echo "Checking TikTok LIVE..."

          while true
          do
            echo "======================================"
            echo "Trying TikTok LIVE..."
            echo "======================================"

            streamlink \
              --loglevel info \
              --retry-streams 10 \
              --retry-max 0 \
              --retry-open 10 \
              --stream-segment-attempts 10 \
              --stream-segment-timeout 30 \
              --stream-timeout 120 \
              "$TIKTOK_URL" \
              best \
              --stdout | \
            ffmpeg \
              -hide_banner \
              -loglevel info \
              -i pipe:0 \
              -c:v libx264 \
              -preset veryfast \
              -pix_fmt yuv420p \
              -b:v 4500k \
              -maxrate 4500k \
              -bufsize 9000k \
              -r 30 \
              -g 60 \
              -keyint_min 60 \
              -sc_threshold 0 \
              -c:a aac \
              -b:a 128k \
              -ar 44100 \
              -f flv \
              "rtmps://a.rtmps.youtube.com/live2/${YOUTUBE_STREAM_KEY}"

            echo "TikTok connection ended."
            echo "Retrying in 15 seconds..."
            sleep 15
          done
