- name: TikTok to YouTube
        env:
          TIKTOK_URL: ${{ secrets.TIKTOK_URL }}
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: |
          echo "Checking TikTok LIVE..."

          streamlink \
            --loglevel info \
            "$TIKTOK_URL" \
            best \
            --stdout | \
          ffmpeg \
            -hide_banner \
            -loglevel info \
            -i pipe:0 \
            -c copy \
            -f flv \
            "rtmps://a.rtmps.youtube.com/live2/${YOUTUBE_STREAM_KEY}"
